version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --protected-mode yes
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks: [appnet]
    # mở cho localhost nếu cần CLI từ host:
    ports:
      - "127.0.0.1:6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - RI_APP_HOST=0.0.0.0
      # - TZ=Asia/Ho_Chi_Minh           # tùy chọn
    ports:
      - "5540:5540"          # nếu cổng bận, đổi thành "5540:8001"
    networks: [appnet]

volumes:
  redis_data:

networks:
  appnet:
